export const FORM_PROJECT = 'FORM_PROJECT'
export const GET_PROJECTS = 'GET_PROJECTS'
export const ADD_PROJECT = 'ADD_PROJECT'
export const SHOW_ERR_FORM = 'SHOW_ERR_FORM'
export const CURRENT_PROJECT = 'CURRENT_PROJECT'
export const DELETE_PROJECT = 'DELETE_PROJECT'

export const TASKS_PROJECT = 'TASKS_PROJECT'